apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-nginx-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dev-nginx-app
  template:
    metadata:
      labels:
        app: dev-nginx-app
    spec:
      volumes:
        - name: assetsdir-volume
          hostPath:
            path: '/dev-host-dir/minikube-dev-stack/dev-nginx/assetsdir'
        - name: ssldir-volume
          hostPath:
            path: '/dev-host-dir/minikube-dev-stack/dev-nginx/ssldir'
      containers:
        - name: dev-nginx-container 
          image: dev-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: app-port-pub
              containerPort: 8080
            - name: app-port-priv
              containerPort: 8181
            - name: app-port-ssl
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /nginxhealth
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 2
            timeoutSeconds: 5
          volumeMounts:
            - name: assetsdir-volume
              mountPath: '/var/www/html/public/assetsdir'
            - name: ssldir-volume
              mountPath: '/etc/customssl/live'
          env:
            - name: NGINX_LOCATION_RESOLVER
              value: 'kube-dns.kube-system'
            - name: NGINX_SERVICE_NAME_FQDN_ADDITION
              value: '.default.svc.cluster.local'
