apiVersion: v1
kind: Service
metadata:
  name: dev-nginx
spec:
  selector:
    app: dev-nginx-app
  ports:
    - name: app-port-pub
      port: 8080
    - name: app-port-priv
      port: 8181
    - name: app-port-ssl
      port: 8443
