apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-mysql-app
  template:
    metadata:
      labels:
        app: dev-mysql-app
    spec:
      volumes:
        - name: dbdir-volume
          hostPath:
            path: '/dev-host-dir/minikube-dev-stack/dev-mysql/dbdir'
      containers:
        - name: dev-mysql-container
          image: dev-mysql
          imagePullPolicy: IfNotPresent
          ports:
            - name: app-port
              containerPort: 3306
          volumeMounts:
            - name: dbdir-volume
              mountPath: '/var/lib/mysql'
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'mypass'
            - name: MYSQL_DATABASE
              value: 'mydb'
