apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-memcached-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-memcached-app
  template:
    metadata:
      labels:
        app: dev-memcached-app
    spec:
      containers:
        - name: dev-memcached-container
          image: dev-memcached
          imagePullPolicy: IfNotPresent
          ports:
            - name: app-port
              containerPort: 11211
