apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-pgsql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-pgsql-app
  template:
    metadata:
      labels:
        app: dev-pgsql-app
    spec:
      containers:
        - name: dev-pgsql-container
          image: dev-pgsql
          imagePullPolicy: IfNotPresent
          ports:
            - name: app-port
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: mypass
            - name: POSTGRES_DB
              value: mydb
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
