apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-pgsql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-pgsql-app
  template:
    metadata:
      labels:
        app: dev-pgsql-app
    spec:
      volumes:
        - name: dbdir-volume
          hostPath:
            path: '/dev-host-dir/minikube-dev-stack/dev-pgsql/dbdir'
      containers:
        - name: dev-pgsql-container
          image: dev-pgsql
          imagePullPolicy: IfNotPresent
          ports:
            - name: app-port
              containerPort: 5432
          volumeMounts:
            - name: dbdir-volume
              mountPath: '/var/lib/postgresql/data/pgdata'
          env:
            - name: POSTGRES_USER
              value: 'root'
            - name: POSTGRES_PASSWORD
              value: 'mypass'
            - name: POSTGRES_DB
              value: 'mydb'
            - name: PGDATA
              value: '/var/lib/postgresql/data/pgdata'
