apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-rabbitmq-app
  template:
    metadata:
      labels:
        app: dev-rabbitmq-app
    spec:
      containers:
        - name: dev-rabbitmq-container
          image: dev-rabbitmq
          imagePullPolicy: IfNotPresent
          ports:
            - name: app-port
              containerPort: 5672
            - name: ui-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: root
            - name: RABBITMQ_DEFAULT_PASS
              value: mypass
            - name: RABBITMQ_ERLANG_COOKIE
              value: mysecret
